# Configuration file (MOST important file)
# Helm chart values for FastAPI app
# Provides all the variables that the templates use

replicaCount: 2 # create 2 pods

image: # tells Kubernetes which Docker image to pull
  repository: "" # Will be overridden by CI/CD pipeline
  tag: "" # Will be overridden by CI/CD pipeline
  pullPolicy: IfNotPresent # Pull the image if not already present on node

service: # creates a public AWS Load Balancer (ELB/NLB) in front of my pods
  type: LoadBalancer
  port: 80

# My FastAPI app is exposed at port 8000 IN DOCKER
# But in Kubernetes, I can STANDARDIZE it to any port I want (8080)
containerPort: 8080
